---
- name: Load Fedora Distro Variables
  include_vars:
    file: 'fedora.yml'
  when: ansible_distribution == 'Fedora'
- name: Load Debian Distro Variables
  include_vars:
    file: 'debian.yml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Install kde packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ kde_packages }}'
  when: kde_packages is defined
- name: Purge packages
  package:
    name: '{{ item }}'
    state: absent
  with_items: '{{ packages_to_purge }}'
  when: packages_to_purge is defined
