---
- name: Install development tools
  become: true
  become_user: root
  become_method: sudo
  package:
    name: '{{ item }}'
    state: 'present'
  with_items: '{{development_common_packages}}'
- name: Enable Docker service
  block:
    - name: just force systemd to reread configs
      systemd:
        daemon_reload: yes
    - name: 'enable docker'
      systemd:
        name: docker
        state: enabled
        enabled: yes
    - name: 'start docker'
      systemd:
        name: docker
        state: started
        enabled: yes
  when: enable_docker ==  "yes"

- name:
  become: true
  become_user: root
  become_method: sudo

- name: Install docker-compose on debian
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: download docker-compose
      raw: sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      ignore_errors: yes
    - name: apply executable permissions
      raw: chmod +x /usr/local/bin/docker-compose
      ignore_errors: yes
  when: ansible_os_family == "Debian"
