---
- name: Install javascript development tools for Red Hat Based
  become: true
  become_user: root
  become_method: sudo
  package:
    name={{ item }}
    state=installed
  with_items:
    -  'nodejs'
  when: ansible_os_family == "RedHat"

- name: Install javascript development tools for Debian Based
  become: true
  become_user: root
  become_method: sudo
  package:
    name={{ item }}
    state=installed
  with_items:
    -  'nodejs'
  when: ansible_os_family == "Debian"