---
- name: Install php development tools
  become: true
  become_user: root
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{php_packages}}'

- name: setup php composer and needed tools
  block:
    - name: Installing composer
      become: true
      become_user: root
      become_method: sudo
      raw: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - name: Installing needed composer packages
      become_user: '{{ username }}'
      raw: composer global require {{ item }}
      with_items:
        - 'phpunit/phpunit'
        - 'phing/phing'
        - 'sebastian/phpcpd'
        - 'phploc/phploc'
        - 'phpmd/phpmd'
        - 'squizlabs/php_codesniffer'
