---
- name: Install development tools for Red Hat Based
  become: true
  become_user: root
  become_method: sudo
  package:
    name={{ item }}
    state=installed
  with_items:
    -  'python-virtualenvwrapper'
  when: ansible_os_family == "RedHat"

- name: Install development tools for debian Based
  become: true
  become_user: root
  become_method: sudo
  package:
    name={{ item }}
    state=installed
  with_items:
    -  'virtualenvwrapper'
  when: ansible_os_family == "Debian"