---
- name: Install development tools for Fedora Based
  become: true
  become_user: root
  become_method: sudo
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - 'python3-virtualenvwrapper'
    - 'python3-pip'
  when: ansible_distribution == "Fedora"
- name: Install development tools for debian Based
  become: true
  become_user: root
  become_method: sudo
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - 'virtualenvwrapper'
    - 'python-pip'
    - 'python3-pip'
  when: ansible_os_family == "Debian"
- name: Install cookicutter python
  raw: pip install --user cookiecutter
