---
- name: Add Custom repos for Fedora Based
  block:
    - name: 'Install copr tools'
      dnf:
        name: ['fedora-workstation-repositories', 'dnf-plugins-core']
        state: present
    - name: 'Set copr repos'
      community.general.copr:
        state: enabled
        name: '{{ item }}'
      with_items: '{{ copr_repos }}'
    - name: 'Set repos'
      dnf:
        name: '{{ rpm_repos }}'
        state: present
        disable_gpg_check: true
      with_items: '{{ rpm_repos }}'
    - name: Tweak dnf settings
      template:
        src: dnf.j2
        dest: /etc/dnf/dnf.conf
        mode: 0644
    - name: Purge packages
      package:
        name: '{{ item }}'
        state: absent
      with_items: '{{ packages_to_purge }}'
      when: packages_to_purge is defined
    - name: Upgrade Fedora
      dnf:
        name: '*'
        state: latest
      tags:
        - skip_ansible_lint
  when: ansible_distribution == 'Fedora'
