# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

ZSH_CUSTOM=~/.config/zsh

plugins=(git common-aliases docker rails tmux vagrant docker history perl rvm python)

# User configuration

export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:~/.composer/vendor/bin"

source $ZSH/oh-my-zsh.sh

#export TERM=xterm-255color
stty -ixon
setxkbmap pt


export NVM_DIR="/home/rubemlrm/bin/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

source /home/rubemlrm/bin/rvm/scripts/rvm
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
