---
- name: Setup Javascript environment
  become: true
  become_user: '{{ username }}'
  block:
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
      args:
        creates: "/home/{{ username }}/.nvm/nvm.sh"
      tags:
        - skip_ansible_lint

    - name: "install node"
      shell: >
        . "/home/{{ username }}/.nvm/nvm.sh" && nvm install {{ item }}
      args:
        executable: /bin/zsh
        chdir: "/home/{{ username }}"
        creates: "/home/{{ username }}/.nvm/versions/{{ item }}"
      loop:
        - node
    - name: Install nodejs modules
      shell: >
        . "/home/{{ username }}/.nvm/nvm.sh" && $(command -v npm) install {{ item }}
      args:
        executable: /bin/zsh
        chdir: "/home/{{ username }}"
      loop: '{{ nodejs_packages }}'
    - name: set user permissions for nvm
      file: dest=/home/{{ username }}/.nvm owner={{ username }} group={{ username }} mode=u=rwX,g=rX,o=rX recurse=yes
