fedora:
    image: fubarhouse/docker-fedora26-ansible
    script:
     - ansible-playbook setup.yml -i tests/inventory --syntax-check
     - ansible-playbook setup.yml -i tests/inventory --connection=local

debian:
    image: williamyeh/ansible:debian9
    script:
     - ansible-playbook setup.yml -i tests/inventory --syntax-check
     - ansible-playbook setup.yml -i tests/inventory --connection=local
