---
language: python
python: "2.7"

sudo: required
dist: trusty
services:
  - docker

matrix:
  include:
    - language: python
      before_install:
        - 'sudo docker run -it --name=fedora26 --privileged --detach --volume="${PWD}":/data:rw fubarhouse/docker-fedora26-ansible bash'

      script:
        # 1. Syntax check
        - "sudo docker exec fedora26 ansible-playbook /data/setup.yml -i tests/inventory --syntax-check"

        # 2. Run playbook to execute role
        - "sudo docker exec fedora26 ansible-playbook /data/setup.yml -i tests/inventory --connection=local"
    - language: python
      before_install:
        - 'sudo docker run -it --name=debian9 --privileged --detach --volume="${PWD}":/data:rw williamyeh/ansible:debian9 bash'

      script:
        # 1. Syntax check
        - "sudo docker exec debian9 ansible-playbook /data/setup.yml -i tests/inventory --syntax-check"

        # 2. Run playbook to execute role
        - "sudo docker exec debian9 ansible-playbook /data/setup.yml -i tests/inventory --connection=local"
