---
language: python
python: '2.7'

sudo: required
dist: trusty
services:
  - docker

matrix:
  include:
    # Fedora
    - name: 'Fedora 31 - cli'
      language: python
      before_install:
        - 'sudo docker run -it --name=fedora31-cli --privileged --detach --volume="${PWD}":/data:rw fubarhouse/docker-ansible:fedora-31 bash'
      script:
        # 1. Syntax check
        - 'sudo docker exec fedora31-cli ansible-playbook /data/setup-cli-test.yml -i tests/inventory --syntax-check'

        # 2. Run playbook to execute role
        - 'sudo docker exec fedora31-cli ansible-playbook -e "password=teste123" /data/setup-cli-test.yml -i tests/inventory --connection=local'
    - name: 'Fedora 31 - Desktop'
      language: python
      before_install:
        - 'sudo docker run -it --name=fedora31-desktop --privileged --detach --volume="${PWD}":/data:rw fubarhouse/docker-ansible:fedora-31 bash'
      script:
        # 1. Syntax check
        - 'sudo docker exec fedora31-desktop ansible-playbook /data/setup-desktop-test.yml -i tests/inventory --syntax-check'

        # 2. Run playbook to execute role
        - 'sudo docker exec fedora31-desktop ansible-playbook -e "password=teste123" /data/setup-desktop-test.yml -i tests/inventory --connection=local'
