---
language: python
python: "2.7"

sudo: required
dist: trusty
services:
  - docker

env:
  - distribution: fedora
    version: 26
  - distribution: Debian
    version: jessie

before_install:
  - 'sudo docker run -it --name=test_dummy --privileged --detach --volume="${PWD}":/etc/ansible/setup.yml:rw cyverse/ansible-test:latest-${distribution}-${version} bash'

script:
  # 1. Syntax check
  - "sudo docker exec test_dummy ansible-playbook /etc/ansible/setup.yml -i tests/inventory --syntax-check"

  # 2. Run playbook to execute role
  - "sudo docker exec test_dummy ansible-playbook /etc/ansible/setup.yml -i tests/inventory --connection=local"

