---
language: python
python: '2.7'

sudo: required
dist: trusty
services:
  - docker

matrix:
  include:
    # Fedora
    - name: 'Fedora 30'
      language: python
      before_install:
        - 'sudo docker run -it --name=fedora30 --privileged --detach --volume="${PWD}":/data:rw fubarhouse/docker-ansible:fedora-30 bash'
      script:
        # 1. Syntax check
        - 'sudo docker exec fedora30 ansible-playbook /data/setup-test.yml -i tests/inventory --syntax-check'

        # 2. Run playbook to execute role
        - 'sudo docker exec fedora30 ansible-playbook -e "password='teste123'" /data/setup-test.yml -i tests/inventory --connection=local'
