---
language: python
python: '2.7'

sudo: required
dist: trusty
services:
  - docker

matrix:
  include:
    # Fedora
    - name: 'Fedora - cli'
      language: python
      before_install:
        - 'sudo docker run -it --name=fedora-cli --privileged --detach --volume="${PWD}":/data:rw fedora:31 bash'
        - 'sudo docker exec fedora-cli dnf install -y ansible git'
      script:
        # 1. Syntax check
        - 'sudo docker exec fedora-cli ansible-playbook /data/setup-cli-test.yml -i tests/inventory --syntax-check'

        # 2. Run playbook to execute role
        - 'sudo docker exec fedora-cli ansible-playbook -e "password=teste123" /data/setup-cli-test.yml -i tests/inventory --connection=local'
    - name: 'Fedora - Desktop'
      language: python
      before_install:
        - 'sudo docker run -it --name=fedora-desktop --privileged --detach --volume="${PWD}":/data:rw fedora:31 bash'
        - 'sudo docker exec fedora-desktop dnf install -y ansible git'
      script:
        # 1. Syntax check
        - 'sudo docker exec fedora-desktop ansible-playbook /data/setup-desktop-test.yml -i tests/inventory --syntax-check'

        # 2. Run playbook to execute role
        - 'sudo docker exec fedora-desktop ansible-playbook -e "password=teste123" /data/setup-desktop-test.yml -i tests/inventory --connection=local'
