---
- hosts: localhost
  vars_files:
    - variables/base.yml
  roles:
    - { role: 'custom-repo/{{ ansible_distribution }}.yml' }
    - { role: base-packages }
    - { role: user-configs }
    - { role: development-tools }
