---
- hosts: workstations
  roles:
    - apt
    - dnf
    - common_cli
    - users
    - common_desktop
    - docker
    - gnome
    - kde
    - nvm
    - php
    - python
    - openssh
    - resolvconf
    - ufw

- hosts: raspberry
  roles:
    - apt
    - common_cli
    - users
    - docker
    - openssh
    - resolvconf
    - ufw

- hosts: wsl
  roles:
    - apt
    - common_cli
    - users
    - nvm
    - php
    - python
