---
- hosts: workstations
  vars_files:
    - variables/base.yml
    - variables/workstation.yml
  roles:
    - base_setup
    - user_configs
    - development_tools
    - desktop
- hosts: raspberry
  vars_files:
    - variables/base.yml
    - variables/raspberry.yml
  roles:
    - base_setup
    - user_configs
    - development_tools

- hosts: wsl
  vars_files:
    - variables/wsl.yml
  roles:
    - base_setup
    - user_configs
    - development_tools
