---
- hosts: localhost
  vars_files:
    - variables/dojo.yml
    - variables/base.yml
    - variables/cli_packages.yml
    - variables/development_packages.yml
    - variables/desktop_packages.yml
    - variables/gnome.yml
  roles:
    - { role: custom_repos }
    - { role: base_packages }
    - { role: desktop_packages}
    - { role: user_configs }
    - { role: development_tools }
