---
- hosts: workstation
  vars_files:
    - variables/dojo.yml
    - variables/base.yml
  roles:
    - base_setup
    - user_configs
    - development_tools
    - kewlfft.aur
    - desktop

- hosts: server
  vars_files:
    - variables/dojo.yml
    - variables/base.yml
  roles:
    - base_setup
    - user_configs
    - development_tools

- hosts: raspberry
  vars_files:
    - variables/rpi.yml
    - variables/base.yml
  roles:
    - base_setup
    - user_configs
    - development_tools
