---
- hosts: workstations
  become: true
  roles:
    - resolvconf
    - apt
    - dnf
    - common_cli
    - openssh
    - users
    - nodejs
    - php
    - python
    - docker
    - common_desktop

- hosts: raspberry
  become: true
  roles:
    - resolvconf
    - apt
    - dnf
    - common_cli
    - openssh
    - users

- hosts: wsl
  become: true
  roles:
    - apt
    - dnf
    - common_cli
    - users
    - nodejs
    - php
    - python
