---
- hosts: workstations
  vars_files:
    - variables/base.yml
    - variables/workstation.yml
  roles:
    - apt
    - dnf
    - common_cli
    - common_desktop
    - docker
    - flatpak
    - gnome
    - kde
    - nvm
    - php
    - python
    - openssh
    - resolvconf
    - ufw

- hosts: raspberry
  vars_files:
    - variables/base.yml
    - variables/raspberry.yml
  roles:
    - apt
    - common_cli
    - docker
    - openssh
    - resolvconf
    - ufw

- hosts: wsl
  vars_files:
    - variables/wsl.yml
  roles:
    - apt
    - common_cli
    - docker
    - nvm
    - php
    - python
