---
- hosts: localhost
  vars:
      - username: rubemlrm
      - home_dir: /home/rubemlrm
      - configs_dir: /home/rubemlrm/bin/dotfiles/roles/user-configs/files  
  roles:
    - { role: base-packages}
    - { role: custom-repos}
    - { role: user-configs}
 

