---
- hosts: workstations
  become: true
  roles:
    - apt
    - dnf
    - users
    - common_cli
    - common_desktop
    - docker
    - gnome
    - kde
    - nvm
    - php
    - python
    - openssh
    - resolvconf
    - ufw

- hosts: raspberry
  become: true
  roles:
    - apt
    - users
    - common_cli
    - openssh
    - ufw

- hosts: wsl
  become: true
  roles:
    - apt
    - users
    - common_cli
    - nvm
    - php
    - python
