---
- hosts: localhost
  vars_files:
    - tests/test-base.yml
    - variables/cli_packages.yml
    - variables/development_packages.yml

  roles:
    - { role: custom-repos }
    - { role: base-packages }
    - { role: user-configs }
    - { role: development-tools }
