---
base_packages:
  - '@virtualization'
  - '@C Development Tools and Libraries'
  - acpi
  - aspell
  - aspell-pt
  - automake
  - cmake
  - ctags
  - gcc-c++
  - gcc
  - git
  - htop
  - powerline-fonts
  - powerline
  - python-devel
  - python3-devel
  - ruby
  - tmux-powerline
  - tmux
  - util-linux-user
  - vim-powerline
  - vim
  - nano
  - zsh
  - numlockx
  - wget
  - exfat-utils
  - lm_sensors
  - screenfetch
  - python3-devel
  - python3-pip
  - python3-inotify
  - python3-gobject
  - python3-oauth2client
  - libcurl-devel
  - dotnet-sdk-3.1
  - npm

font_packages:
  - adobe-source-code-pro-fonts
  - fira-code-fonts
  - mozilla-fira-*
  - fontawesome-fonts
  - hack-fonts

copr_repos:
  - zawertun/hack-fonts
  - evana/fira-code-fonts
  - dirkdavidis/papirus-icon-theme
  - '@dotnet-sig/dotnet'

rpm_repos:
  - 'http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version }}.noarch.rpm'
  - 'http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version }}.noarch.rpm'
