---
- name: Load Distro Variables
  include_vars:
    file: '{{ ansible_distribution | lower }}.yml'
- include_tasks: snaps.yml
  name: snaps
  when: use_snap
- include_tasks: flatpak.yml
  name: flatpak
  when: use_flatpak
- include_tasks: kde.yml
  name: kde setup
- include_tasks: utils.yml
  name: desktop utils install
