---
- name: Load Distro Variables
  include_vars:
    file: '{{ansible_os_family | lower}}.yml'
- include_tasks: snaps.yml
  name: snaps
  when: use_snap
- include_tasks: kde.yml
  name: kde setup
  when: use_kde
- include_tasks: utils.yml
  name: desktop utils install
