---
- name: Load Debian based Distro Variables
  include_vars:
    file: 'debian.yml'
  when: ansible_os_family == 'Debian'
- name: Load Fedora based Distro Variables
  include_vars:
    file: 'fedora.yml'
  when: ansible_distribution == 'Fedora'
- include_tasks: snaps.yml
  name: snaps
  when: use_snap
- include_tasks: kde.yml
  name: kde setup
- include_tasks: utils.yml
  name: desktop utils install
