---

- name: Install desktop packages
  become: true
  become_user: root
  become_method: sudo
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{desktop_packages}}'
  when: desktop_packages is defined

- name: install gnome themes
  become: true
  become_user: root
  become_method: sudo
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{gtk_themes}}'
  when: gtk_themes is defined
