- name: Add Custom repos for Debian Based
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: get arch
      shell: dpkg --print-architecture
      register: get_arch
    - set_fact: arch="{{get_arch.stdout}}"
    - name: Install gpg agent for ubuntu
      package:
        name: 'gpg-agent'
        state: 'present'
      when: ansible_distribution == "Ubuntu"
    - name: Add gpg keys
      apt_key:
        url: '{{ item }}'
        state: 'present'
      with_items:
        - 'https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg'
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    - name: Add gpg keys for raspberry
      apt_key:
        url: '{{ item }}'
        state: 'present'
      with_items:
        - 'https://download.docker.com/linux/debian/gpg'
      when: ansible_distribution == "ClearLinux" or ansible_distribution == "Raspbian"
    - name: Add repos
      apt_repository:
        repo: '{{ item }}'
        state: 'present'
      with_items:
        - 'deb [arch={{arch}}] https://download.docker.com/linux/{{ansible_distribution | lower}} {{ansible_distribution_release}} stable'
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    - name: Add repos
      apt_repository:
        repo: '{{ item }}'
        state: 'present'
      with_items:
        - 'deb [arch={{arch}}] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable'
      when: ansible_distribution == "ClearLinux" or ansible_distribution == "Raspbian"
    - name: update repos
      apt:
        name: '*'
        state: latest
        update_cache: yes
        force_apt_get: yes
    - name: add repos with curl
      raw: '{{ item }}'
      with_items:
        - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
