---
- name: Add Custom repos for Fedora Based
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: 'install copr tools'
      dnf:
        name: ['fedora-workstation-repositories', 'dnf-plugins-core']
        state: present
    - name: 'set copr repos'
      command: 'dnf copr enable {{item}} -y'
      with_items:
        - 'evana/fira-code-fonts'
        - 'daniruiz/flat-remix'
    - name: 'set workstation repos'
      command: 'dnf config-manager --set-enabled  {{item}} -y'
      with_items:
        - 'google-chrome'
    - name: 'set repos'
      dnf:
        name:
          [
            'http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_version }}.noarch.rpm',
            'http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_version }}.noarch.rpm',
          ]
        state: present
