---
- name: Add Custom repos for Fedora Based
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: 'install copr tools'
      dnf:
        name: ['fedora-workstation-repositories', 'dnf-plugins-core']
        state: present
    - name: 'set copr repos'
      command: 'dnf copr enable {{item}} -y'
      with_items: '{{copr_repos}}'

    - name: 'set workstation repos'
      command: 'dnf config-manager --set-enabled  {{item}} -y'
      with_items:
        - 'google-chrome'
    - name: 'set repos'
      dnf:
        name: '{{item}}'
        state: present
      with_items: '{{rpm_repos}}'
- name: Upgrade Fedora
  become: true
  become_user: root
  become_method: sudo
  dnf:
    name: '*'
    state: latest
