---
- name: Add Custom repos for Red Hat Based
  become: true
  become_user: root
  become_method: sudo
  yum_repository:
    name:  item.name
    description: item.description
    file: item.file
    baseurl: item.baseurl
  with_items:
    - { 
        name: "docker", 
        description: "docker oficial repo", 
        file: "docker-ce.repo", 
        baseurl: "https://download.docker.com/linux/fedora/docker-ce.repo"
        }
  when: ansible_os_family == "RedHat"
