gtk_themes:

kde_packages:
  - plasma
  - spectacle
  - dolphin
  - dolphin-plugins
  - ark
  - kio-extras
  - kio-gdrive
  - okular
  - kaccounts-providers
  - sddm
  - sddm-kcm

desktop_packages:
  - chromium
  - thunderbird
  - lutris
  - telegram-desktop
  - papirus-icon-theme
  - terminator
  - libreoffice-still
  - libreoffice-still-pt
  - calibre
  - filezilla
  - firefox
  - firefox-developer-edition
  - code
  - discord
  - gimp
  - timeshift
  - steam
  - partitionmanager

aur_packages:
  - bitwarden
  - visual-studio-code-insiders
  - rpi-imager
