desktop_packages:
  - 'thunderbird'
  - 'google-chrome-stable'
  - 'lutris'
  - 'telegram-desktop'
  - 'papirus-icon-theme'
  - 'terminator'
  - 'libreoffice'
  - 'calibre'
  - 'steam'
  - 'filezilla'
  - 'firefox'
  - 'paper-icon-theme'
  - 'numix-icon-theme-circle'
  - 'flat-remix-icon-theme'
  - 'gimp'
  - 'timeshift'
  - 'chromium-browser'

kde_packages:
  - 'kio-gdrive'
  - 'kaccounts-providers'
