---
- name: Install openssh
  package:
    name: 'openssh-server'
    state: present
- name: Copy ssh custom configs
  template:
    src: '{{ item.origin_name }}'
    dest: /etc/ssh/{{ item.file_name }}
    mode: 0644
  with_items:
    - origin_name: ssh_config.j2
      file_name: ssh_config
    - origin_name: sshd_config.j2
      file_name: sshd_config
  notify:
    - Enable openssh server
    - Restart openssh server
- name: Setup selinux for custom ssh port
  seport:
    ports: '{{ ssh_port }}'
    proto: 'tcp'
    setype: 'ssh_port_t'
    state: 'present'
  when: ansible_selinux is defined and ansible_selinux is not false and ansible_selinux.status == 'enabled'
  notify:
    - Restart openssh server
- name: Tweak SSH rules on firewall on Fedora
  block:
    - name: Remove old firewall rule
      firewalld:
        service: ssh
        permanent: yes
        immediate: yes
        state: disabled
    - name: Enable firewall rule
      firewalld:
        port: '{{ ssh_port }}/tcp'
        permanent: yes
        immediate: yes
        state: enabled
  when: ansible_distribution == 'Fedora'
- name: Tweak SSH rules on firewall on Debian based
  block:
    - name: Workaround for ipv6
      shell: update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
      tags:
        - skip_ansible_lint
    - name: Enable ufw
      ufw:
        state: enabled
        policy: allow
        logging: true
    - name: Enable firewall rule
      ufw:
        rule: allow
        port: '{{ ssh_port }}'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
