---
- name: Install nodejs in debian based distros
  block:
    - name: Add nodejs repo key
      apt_key:
        url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
        state: 'present'
    - name: Add Nodejs Repo
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Install nodejs
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
- name: Setup Javascript environment
  become: true
  become_user: '{{ username }}'
  npm:
    name: "{{ item }}"
    state: present
    path: "/home/{{ username }}/bin/node_modules"
  with_items: "{{ nodejs_packages }}"