- name: Add Custom repos for Debian Based
  become: true
  become_method: sudo
  block:
    - name: update repos to install ca-certificates and https-transport
      apt:
        name: '*'
        state: latest
        update_cache: yes
        force_apt_get: yes
    - name: install ca-certificates and https-transport
      package:
        name: '{{ item }}'
        state: present
      with_items:
        - 'apt-transport-https'
        - 'ca-certificates'
    - name: get arch
      shell: dpkg --print-architecture
      register: get_arch
    - set_fact: arch="{{get_arch.stdout}}"
    - name: Add gpg keys
      apt_key:
        url: '{{ item }}'
        state: 'present'
      with_items:
        - 'https://download.docker.com/linux/debian/gpg'
        - 'https://packages.sury.org/php/apt.gpg'
