---
- name: Add Custom repos for Fedora Based
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: 'install copr tools'
      dnf:
        name: ['fedora-workstation-repositories', 'dnf-plugins-core']
        state: present
    - name: 'set copr repos'
      command: 'dnf copr enable {{item}} -y'
      with_items: '{{copr_repos}}'
    - name: 'set workstation repos'
      command: 'dnf config-manager --set-enabled  {{item}} -y'
      with_items:
        - 'google-chrome'
    - name: 'set repos'
      dnf:
        name: '{{rpm_repos}}'
        state: present
        disable_gpg_check: true
      with_items: '{{rpm_repos}}'
    - name: 'setup vscode'
      yum_repository:
        name: vscode
        description: vscode repo
        file: vscode
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: yes
        enabled: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
- name: Tweak dnf settings
  template:
    src: dnf.j2
    dest: /etc/dnf/dnf.conf
- name: Upgrade Fedora
  become: true
  become_user: root
  become_method: sudo
  dnf:
    name: '*'
    state: latest
