---
- name: Load Distro Variables
  include_vars:
    file: '{{ansible_distribution | lower}}.yml'

- include: apt.yml
  when: ansible_os_family == 'Debian'

- include: dnf.yml
  when: ansible_distribution == 'Fedora'

- include: pacman.yml
  when: ansible_distribution == 'Archlinux'

- include: openssh.yml
- include: resolv.yml
- include: packages.yml
- include: ufw.yml
