- name: Setup Pacman
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: update cache
      pacman:
        update_cache: yes
    - name: install pacman tools
      package:
        name: '{{item}}'
        state: present
      with_items:
        - pacman-contrib
        - base-devel
    - name: upgrade system
      pacman:
        upgrade: true
        update_cache: true
- name: Setup Pacman
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: update cache
      pacman:
        update_cache: yes
    - name: install pacman tools
      package:
        name: '{{item}}'
        state: present
      with_items:
        - pacman-contrib
        - base-devel
        - reflector
    - name: Copy Custom pacman.conf
      template:
        src: pacman.j2
        dest: /etc/pacman.conf
    - name: Enable reflector mirrors
      raw: reflector --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist
    - name: upgrade system
      pacman:
        upgrade: true
        update_cache: true
