---
- name: Load Fedora Distro Variables
  include_vars:
    file: 'fedora.yml'
  when: ansible_distribution == 'Fedora'
- name: Load Debian Distro Variables
  include_vars:
    file: 'debian.yml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Setup Javascript environment
  block:
    - name: Install Python development tools
      package:
        name: '{{ item }}'
        state: present
      with_items: '{{ python_packages }}'
    - name: Install cookicutter python
      become: true
      become_user: '{{ username }}'
      raw: pip3 install --user cookiecutter yamllint virtualenvwrapper ansible ansible-lint Django
