---
- name: Load Fedora Distro Variables
  include_vars:
    file: 'fedora.yml'
  when: ansible_distribution == 'Fedora'
- name: Load Debian Distro Variables
  include_vars:
    file: 'debian.yml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Install base packages
  block:
    - name: Install cli utils
      ansible.builtin.package:
        name: '{{ item }}'
        state: present
      with_items: '{{ base_packages }}'
    - name: Install fonts
      ansible.builtin.package:
        name: '{{ item }}'
        state: present
      with_items: '{{ font_packages }}'
- name: Enable Firewall
  block:
    - name: check firewall status
      ansible.builtin.shell: 'service firewalld status | grep active | wc -l'
      changed_when: false
      register: firewall_running
      tags:
        - skip_ansible_lint
    - name: start firewall
      ansible.builtin.systemd:
        name: firewalld
        enabled: yes
      when: firewall_running.stdout == 0
    - name: set running firewall
      ansible.builtin.systemd:
        name: firewalld
        state: started
  when: use_firewall == true
