---
- name: Load Fedora Distro Variables
  include_vars:
    file: 'fedora.yml'
  when: ansible_distribution == 'Fedora'
- name: Load Debian Distro Variables
  include_vars:
    file: 'debian.yml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Install base packages
  block:
    - name: Install cli utils
      package:
        name: '{{ item }}'
        state: present
      with_items: '{{ base_packages }}'
    - name: Install fonts
      package:
        name: '{{ item }}'
        state: present
      with_items: '{{ font_packages }}'
- name: start firewall
  block:
    - name: Workaround for ipv6
      shell: update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
      tags:
        - skip_ansible_lint
    - name: Enable ufw
      ufw:
        state: enabled
        policy: allow
        logging: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: start firewall
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_distribution == 'Fedora'
