---
- name: Add system user
  user:
    name: '{{ username }}'
    password: "{{ password | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
- name: Change user shell to znc
  raw: chsh {{ username  }} -s /usr/bin/zsh
  ignore_errors: yes

- name: Clone Needed Repos
  git: repo={{item.repo}} dest={{item.dest}}
  with_items:
    - {
        repo: 'https://github.com/robbyrussell/oh-my-zsh.git',
        dest: '/home/{{username}}/.oh-my-zsh',
      }

- name: Created base folders for configs
  file: path={{ home_dir }}/{{item}} state=directory
  with_items:
    - '.config'
    - '.urxvt'
    - '.urxvt/ext'
    - '.dconfBackup'

- name: Restore Configs
  file: src={{ configs_dir }}/{{ item.origin }}
    dest={{ home_dir }}/{{ item.dest }}
    state=link
    force=true
    owner={{username}}
    group={{username}}
  with_items:
    - { origin: 'zsh/zshrc', dest: '.zshrc' }
    - { origin: 'zsh/configs', dest: '.config/zsh' }
    - { origin: 'vim/vimrc', dest: '.vimrc' }
    - { origin: 'vim/vim', dest: '.vim' }
    - { origin: 'Xstuff/Xdefaults', dest: '.Xdefaults' }
    - { origin: 'tmux/tmux.conf', dest: '.tmux.conf' }
    - { origin: 'tmux/configs', dest: '.config/tmux' }
    - { origin: 'dconf', dest: '.dconfBackup' }
