---
- name: Add system user
  user:
    name: '{{ username }}'
    password: "{{ password | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
- name: Change user shell to znc
  raw: chsh {{ username  }} -s /usr/bin/zsh
  ignore_errors: yes



- name: Created base folders for configs
  file: path={{ home_dir }}/{{item}} state=directory
  with_items:
    - '.config'
    - 'bin'

- name: Clone Needed Repos
  git: repo={{item.repo}} dest={{item.dest}}
  with_items:
    - {
        repo: 'https://github.com/Rubemlrm/dotfiles.git',
        dest: '/home/{{username}}/bin/dotfiles',
      }

- name: restore dotfiles
  become: true
  become_user: '{{username}}'
  raw: cd /home/{{username}}/bin/dotfiles && bash bootstrap.sh

- name: set gnome extensions
  block:
    - name: install gnome themes
      become: true
      become_user: root
      become_method: sudo
      package:
        name: '{{ item }}'
        state: present
      with_items: '{{gnome_themes}}'
      when: gnome_themes is defined
    - name: install gnome extension manager
      raw: wget -O gnome-shell-extension-installer https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer
    - name: install gnome-extension manager permissions
      raw: chmod +x gnome-shell-extension-installer
    - name: end gnome extension manager process
      raw: mv gnome-shell-extension-installer /usr/bin/
    - name: install gnome extensions
      raw: gnome-shell-extension-installer {{item}}
      become: true
      become_user: '{{username}}'
      with_items: '{{gnome_extensions}}'
    - name: copy missing schemas
      raw: cp /home/{{username}}/.local/share/gnome-shell/extensions/{{item}} /usr/share/glib-2.0/schemas
      become: true
      become_method: sudo
      become_user: root
      with_items: '{{gnome_schemas_copy}}'
    - name: rebuild gnome schemas cache
      raw: glib-compile-schemas /usr/share/glib-2.0/schemas/
      become: true
      become_method: sudo
      become_user: root
    - name: restore gnome settings
      shell: dbus-launch gsettings set {{item}}
      become: true
      become_user: '{{username}}'
      with_items: '{{gnome_settings}}'
  when: restore_desktop_settings
