kde_packages:
  - 'kio-gdrive'
  - 'kaccounts-providers'
  - 'arc-kde'

packages_to_purge:
  - 'abrt-gui'
  - 'akregator'
  - 'calligra-core'
  - 'calligra-sheets'
  - 'dragonplayer'
  - 'falkon'
  - 'grantlee-editor'
  - 'juk'
  - 'kaddressbook'
  - 'kcolorchooser'
  - 'kget'
  - 'kget'
  - 'kmag'
  - 'kmahjongg'
  - 'kmail'
  - 'kmines'
  - 'kmousetool'
  - 'kmouth'
  - 'kolourpaint'
  - 'kontact'
  - 'konversation'
  - 'korganizer'
  - 'kpat'
  - 'krdc'
  - 'krfb'
  - 'kruler'
  - 'ktnef'
  - 'ktorrent'
  - 'kwrite'
  - 'mediawriter'
  - 'pim-sieve-editor'
