---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: 'common_cli - check package status'
      package:
        name: 'tmux'
        state: 'installed'
      check_mode: yes
      register: pkg_status
    - name: 'common_cli - package is installed'
      assert:
        that:
          - not pkg_status.changed
