---
- name: Restore gpg keys settings
  become: true
  become_user: '{{ username }}'
  when: gpg_trust is defined and gpg_public_keys is defined and gpg_private_keys is defined
  block:
    - name: Check if gpg is already imported
      shell: 'gpg --list-secret-keys | grep {{ gpg_trust }}'
      changed_when: false
      register: gpg_trust_exists  
    - name: Restore gpg public keys
      raw:  echo -e "{{ gpg_public_keys }}" | gpg --import
      when: gpg_trust_exists.stdout is not defined
    - name: Restore gpg private keys
      raw:  echo -e "{{ gpg_private_keys }}" | gpg --batch --import
      when: gpg_trust_exists.stdout is not defined
    - name: Restore trust
      raw:  echo -e "5\ny\n" |  gpg --command-fd 0 --expert --edit-key "{{ gpg_trust }}" trust
      when: gpg_trust_exists.stdout is not defined
      no_log: true
