---
- name: Setup User
  block:
    - name: Add system user
      user:
        name: '{{ username }}'
        password: "{{ password | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        shell: '/usr/bin/zsh'
      no_log: true
    - name: Created base folders for configs
      file: path={{ home_dir }}/{{ item }} state=directory mode=0755 owner={{ username }} group={{ username }}
      with_items:
        - 'tools'
        - 'bin'
        - '.local/share/fonts'
    - name: Remove Users
      user:
        name: '{{ item }}'
        state: absent
      with_items: '{{ disable_users }}'
      when: disable_users is defined
