#other:
use_snap: false
enable_docker: true
restore_desktop_settings: true

copr_repos:
  - 'zawertun/hack-fonts'
  - 'evana/fira-code-fonts'
  - 'dirkdavidis/papirus-icon-theme'
  - '@dotnet-sig/dotnet'

rpm_repos:
  - 'http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_version }}.noarch.rpm'
  - 'http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_version }}.noarch.rpm'
