---
- name: Load Fedora Distro Variables
  include_vars:
    file: 'fedora.yml'
  when: ansible_distribution == 'Fedora'
- name: Load Debian Distro Variables
  include_vars:
    file: 'debian.yml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Import native installer
  import_tasks: native.yml
- name: Import flatpak installer
  import_tasks: flatpak.yml
- name: Import snap installer
  import_tasks: snap.yml
