---
- name: Set Fedora Distro Desktop Extra repositories
  block:
    - name: 'setup vscode'
      yum_repository:
        name: vscode
        description: vscode repo
        file: vscode
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: yes
        enabled: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_distribution == 'Fedora'
- name: Install desktop packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ desktop_packages }}'
  when: desktop_packages is defined
- name: Install distro extra packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ distro_extra_packages }}'
  when: distro_extra_packages is defined
- name: Install gnome themes
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ gtk_themes }}'
  when: gtk_themes is defined
