---
- name: Set Fedora Distro Desktop Extra repositories
  block:
    - name: 'setup vscode'
      ansible.builtin.yum_repository:
        name: vscode
        description: vscode repo
        file: vscode
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: yes
        enabled: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    - name: 'check google chrome repo'
      ansible.builtin.shell: 'dnf repolist enabled | grep google-chrome | wc -l'
      changed_when: false
      register: chrome_repo_is_enabled
      tags:
        - skip_ansible_lint
    - name: 'enable google chrome repo'
      ansible.builtin.shell: 'dnf config-manager --set-enabled google-chrome -y'
      when: chrome_repo_is_enabled.stdout == "0"
      tags:
        - skip_ansible_lint
  when: ansible_distribution == 'Fedora'
- name: Install desktop packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items: '{{ desktop_packages }}'
  when: desktop_packages is defined
- name: Install distro extra packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items: '{{ distro_extra_packages }}'
  when: distro_extra_packages is defined
- name: Install gnome themes
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items: '{{ gtk_themes }}'
  when: gtk_themes is defined
- name: Install kde packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items: '{{ kde_packages }}'
  when: kde_packages is defined
