---
- name: Setup snap
  block:
  - name: Install snap
    package:
      name: 'snapd'
      state: present
  - name: 'Fix snap symlink in fedora'
    file:
      src: "/var/lib/snapd/snap"
      dest: "/snap"
      state: link
    when: ansible_distribution == 'Fedora'
    notify:
    - restart snapd
  - name: 'Install with snap'
    community.general.snap:
      name: "{{ item.name }}"
      classic: "{{ item.classic }}"
    with_items: '{{ snap_packages }}'
    when: snap_packages is defined
