---
- name: Setup snap
  block:
  - name: install snap
    package:
      name: 'snapd'
      state: present
  - name: 'fix snap symlink in fedora'
    file:
      src: "/var/lib/snapd/snap"
      dest: "/snap"
      state: link
    when: ansible_distribution == 'Fedora'
    notify:
    - restart snapd
  - name: 'install with snap'
    command: snap install {{ item.name }} {{ item.classic }}
    with_items: '{{ snap_packages }}'
    when: snap_packages is defined
