- name: restart openssh server
  systemd:
    name: sshd
    state: restarted
  become: true
- name: enable openssh server
  systemd:
    name: sshd
    state: started
  become: true
- name: enable cronie server
  systemd:
    name: cronie
    state: started
  become: true
