---
- name: Setup Docker service
  block:
    - name: 'Install docker'
      package:
        name: '{{ item }}'
        state: 'present'
      with_items: '{{ docker_packages }}'
    - name: 'Just force systemd to reread configs'
      systemd:
        daemon_reload: yes
    - name: 'Start docker'
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: 'Add user to docker group'
      user:
        name: '{{ username }}'
        groups: docker
        append: yes
