---
- name: Load Fedora Distro Variables
  include_vars:
    file: 'fedora.yml'
  when: ansible_distribution == 'Fedora'
- name: Load Debian Distro Variables
  include_vars:
    file: 'debian.yml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: setup php composer and needed tools
  block:
    - name: Install php development tools
      package:
        name: '{{ item }}'
        state: present
      with_items: '{{ php_packages }}'
    - name: install extra php packages
      package:
        name: '{{ item }}'
        state: present
      with_items: '{{ php_extra_packages }}'
      when: php_extra_packages is defined
    - name: Installing composer
      raw: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - name: Installing needed composer packages
      become: true
      become_user: '{{ username }}'
      composer:
       command: require
       global_command: true
       arguments: '{{ item }}'
      with_items: '{{ composer_packages }}'
