---
- name: Copy git config files
  become: true
  become_user: '{{username}}'
  block:
    - name: generate ssh config settings
      template:
        src: ssh_hosts.j2
        dest: '/home/{{username}}/.ssh/config'
        owner: '{{username}}'
        group: '{{username}}'
    - name: restore ssh keys
      copy:
        dest: '/home/{{username}}/.ssh/{{item.name}}_rsa'
        content: '{{item.private }}'
        mode: '0644'
      with_items: "{{ ssh_hosts }}"
    - name: restore ssh keys
      copy:
        dest: '/home/{{username}}/.ssh/{{item.name}}_rsa.pub'
        content: '{{item.public}}'
        mode: '0644'
      with_items: "{{ ssh_hosts }}"
    - name: copy git ignore
      template:
        src: gitignore.j2
        dest: /home/{{username}}/.gitignore
    - name: copy git config
      template:
        src: gitconfig.j2
        dest: /home/{{username}}/.gitconfig
    - name: copy git attributes
      template:
        src: gitattributes.j2
        dest: /home/{{username}}/.gitattributes
