---
- name: Add system user
  user:
    name: '{{ username }}'
    password: "{{ password | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
- name: Change user shell to znc
  raw: chsh {{ username  }} -s /usr/bin/zsh
  ignore_errors: yes

- name: Created base folders for configs
  file: path={{ home_dir }}/{{item}} state=directory
  with_items:
    - '.config'
    - 'bin'

- name: Clone Needed Repos
  git: repo={{item.repo}} dest={{item.dest}}
  with_items:
    - {
        repo: 'https://github.com/Rubemlrm/dotfiles.git',
        dest: '/home/{{username}}/bin/dotfiles',
      }
