---
- name: Created base folders for vim configs
  file: path={{ home_dir }}/{{item}} state=directory
  become: true
  become_user: '{{username}}'
  with_items:
    - '.vim'

- name: Restore vim Configs
  become: true
  become_user: root
  become_method: sudo
  copy:
    src: '{{ playbook_dir }}/roles/user_configs/files/{{ item.origin }}'
    dest: '{{ home_dir }}/{{ item.dest }}'
    force: true
    owner: '{{username}}'
    group: '{{username}}'
  with_items:
    - { origin: 'vim/vimrc', dest: '.vimrc' }
    - { origin: 'vim/vim/', dest: '.vim' }

- name: Download vim plug
  become: true
  become_user: '{{username}}'
  get_url:
    url: '{{item.url}}'
    dest: '{{item.dest}}'
  with_items:
    - {
        url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim',
        dest: '/home/{{username}}/.vim/autoload/plug.vim'
      }
