---

- name: Setup Yay
  become: true
  become_user: '{{username}}'
  block:
    - name: Clone Yay repo
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: '/home/{{username}}/tools/yay'
    - name: Check Yay Existance
      shell: command -v yay >/dev/null 2>&1
      register: yay_exists
      ignore_errors: yes
    - name: Compile Yay
      raw:  cd '/home/{{username}}/tools/yay' && makepkg -si
      when: not yay_exists
