---
- name: setup snap packages
  block:
    - name: Install snap service and packages
      become: true
      package: name=snapd
        state=present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
    - name: 'enable classic mode for snap'
      file:
        src: "/var/lib/snapd/snap"
        dest: "/snap"
        state: link
    - name: just force systemd to reread configs
      systemd:
        daemon_reload: yes
      notify:
        - start snapd
        - enable snapd
    - name: 'install with snap'
      command: snap install {{ item.name }} {{ item.classic }}
      with_items: '{{ snap_packages }}'
