---
- name: Install utils for Red Hat Based
  become: true
  become_user: root
  become_method: sudo
  package:
    name={{ item }}
    state=installed
  with_items:
    -  'util-linux-user'
    -  'tmux'
    -  'git'
    -  'zsh'
    -  'acpi'
    -  'htop'
    -  'vim'
    -  'rxvt-unicode-256color'
    -  'adobe-source-code-pro-fonts'
    -  'powerline'
    -  'powerline-fonts'
    -  'tmux-powerline'
    -  'vim-powerline'
    -  'ctags'
    -  'python-devel'
    -  'python3-devel'
    -  'automake'
    -  'gcc'
    -  'gcc-c++'
    -  'cmake'
    -  'dnf-plugins-core'
  when: ansible_os_family == "RedHat"

- name: Install utils for Debian Based
  become: true
  become_user: root
  become_method: sudo
  package:
    name={{ item }}
    state=installed
  with_items:
    -  'tmux'
    -  'git'
    -  'zsh'
    -  'acpid'
    -  'htop'
    -  'vim'
    -  'rxvt-unicode-256color'
    -  'ctags'
    -  'apt-transport-https'
    -  'ca-certificates'
    -  'curl'
    -  'gnupg2'
    -  'software-properties-common'
    -  'keyboard-configuration'
    -  'console-setup'
    -  'zip'
    -  'unzip'
  when: ansible_os_family == "Debian"
- name: Add system user
  user:
    name: "{{ username }}"
    password: "{{ 'changeme' | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa


