---
# load specific variables
- name: Include OS-specific variables.
  include_vars: '{{ item }}'
  with_fileglob:
    - '{{ playbook_dir }}/variables/packages.yml'

- name: Install base packages
  become: true
  become_user: root
  become_method: sudo
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{base_packages}}'
