---
- name: Install utils for Red Hat Based
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: 'install with dnf'
      package: name={{ item }}
        state=installed
      with_items:
        - '@C Development Tools and Libraries'
        - 'acpi'
        - 'adobe-source-code-pro-fonts'
        - 'automake'
        - 'cmake'
        - 'ctags'
        - 'gcc-c++'
        - 'gcc'
        - 'git'
        - 'gnome-tweak-tool'
        - 'htop'
        - 'powerline-fonts'
        - 'powerline'
        - 'python-devel'
        - 'python3-devel'
        - 'ruby'
        - 'rxvt-unicode-256color'
        - 'snapd'
        - 'thunderbird'
        - 'tmux-powerline'
        - 'tmux'
        - 'util-linux-user'
        - 'vim-powerline'
        - 'vim'
        - 'zsh'
        - 'fira-code-fonts'
        - 'flat-remix'
        - 'flat-remix-gnome'
        - 'flat-remix-gtk'
        - 'google-chrome-stable'
        - 'lutris'
    - name: 'enable classic mode for snap'
      raw: 'ln -sf /var/lib/snapd/snap /snap'
  when: ansible_os_family == "RedHat"

- name: Install utils for Debian Based
  become: true
  become_user: root
  become_method: sudo
  package: name={{ item }}
    state=installed
  with_items:
    - 'tmux'
    - 'git'
    - 'zsh'
    - 'acpid'
    - 'htop'
    - 'vim'
    - 'rxvt-unicode-256color'
    - 'ctags'
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'gnupg2'
    - 'software-properties-common'
    - 'keyboard-configuration'
    - 'console-setup'
    - 'zip'
    - 'unzip'
    - 'git-core'
    - 'curl'
    - 'snapd'
    - 'zlib1g-dev'
    - 'build-essential'
    - 'libssl-dev'
    - 'libreadline-dev'
    - 'libyaml-dev'
    - 'libsqlite3-dev'
    - 'sqlite3'
    - 'libxml2-dev'
    - 'libxslt1-dev'
    - 'libcurl4-openssl-dev'
    - 'libffi-dev'
    - 'ruby-full'
  when: ansible_os_family == "Debian"

- name: Add system user
  user:
    name: '{{ username }}'
    password: "{{ 'changeme' | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes
  when: use_snap == "yes"
- name: 'start snap'
  systemd:
    name: snapd
    state: started
    enabled: yes
  when: use_snap == "yes"
- name: 'install with snap'
  command: snap install {{item.name}} {{item.classic}}
  with_items:
    - name: 'vscode'
      classic: '--classic'
    - name: 'skype'
      classic: '--classic'
    - name: 'discord'
      classic: ''
    - name: 'slack'
      classic: '--classic'
    - name: 'vlc'
      classic: ''
    - name: 'spotify'
      classic: ''
    - name: 'whatsdesk'
      classic: ''
    - name: 'rubymine'
      classic: '--classic'
    - name: 'phpstorm'
      classic: '--classic'
    - name: 'pycharm-professional'
      classic: '--classic'
  when: use_snap == "yes"
