---
- name: Install snap service and packages
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: Install snapd service
      become: true
      become_user: root
      become_method: sudo
      package: name=snapd
        state=present
    - name: 'enable classic mode for snap'
      raw: 'ln -sf /var/lib/snapd/snap /snap'
      when: ansible_distribution == "Fedora"
    - name: just force systemd to reread configs
      systemd:
        daemon_reload: yes
    - name: 'enable snap'
      systemd:
        name: snapd
        state: enabled
        enabled: yes
    - name: 'start snap'
      systemd:
        name: snapd
        state: started
        enabled: yes
    - name: 'install with snap'
      command: snap install {{item.name}} {{item.classic}}
      with_items:
        - name: 'discord'
          classic: ''
        - name: 'slack'
          classic: '--classic'
        - name: 'spotify'
          classic: ''
        - name: 'rubymine'
          classic: '--classic'
        - name: 'phpstorm'
          classic: '--classic'
        - name: 'pycharm-professional'
          classic: '--classic'
