---
- name: Setup Docker service
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: 'install docker'
      package:
        name: '{{ item }}'
        state: 'present'
      with_items: '{{docker_packages}}'
    - name: 'just force systemd to reread configs'
      systemd:
        daemon_reload: yes
    - name: 'start docker'
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: 'add user to docker group'
      user:
        name: '{{ username }}'
        groups: docker
        append: yes
  when: use_docker
