---
- name: Install nodejs
  become: true
  become_user: root
  become_method: sudo
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - 'nodejs'
    - 'npm'

- name: Install nodejs modules
  become: true
  become_user: root
  become_method: sudo
  npm:
    name: '{{ item }}'
    global: yes
  with_items: '{{nodejs_packages}}'
