---
- name: Install nodejs
  become: true
  become_user: root
  become_method: sudo
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - 'nodejs'

- name: Install nodejs modules
  become: true
  become_user: '{{username}}'
  npm:
    name: '{{ item }}'
    global: yes
  with_items: '{{nodejs_packages}}'

