---

- include_tasks: docker.yml
  name: docker settings
- include_tasks: javascript.yml
  name: javascript tools and libs
- include_tasks: php.yml
  name: php tools and libs
- include_tasks: python.yml
  name: python tools and libs
