- name: Install base packages
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: install cli utils
      package:
       name: '{{ item }}'
       state: present
      with_items: '{{ base_packages }}'
    - name: install fonts
      package:
       name: '{{ item }}'
       state: present
      with_items: '{{ font_packages }}'
